name: simply_easy_layout
description: Yet another Easy Layout package which helps you get a relative width and height from fixed_layout.
version: 0.1.8
homepage: https://github.com/chan150/simply_easy_layout

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.3.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1