name: simply_easy_layout
description: Yet another Easy Layout package which helps you get a relative width and height from fixed_layout.
version: 0.6.0
homepage: https://github.com/chan150/simply_easy_layout

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.7"

dependencies:
  flutter:
    sdk: flutter
